---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://blog.tiramisu.solutions"
staticdir: "static"
#canonifyurls: true
title: "DevOps - Documentation - Hosting"
params:
    MastheadTitle: "Random thoughts"
...
